### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by mbhall88** [mcveanlab/mccortex#75]
I am encountering an issue during build on Ubuntu 18.04

```sh
apt install -y liblzma-dev libbz2-dev libz-dev libncurses5-dev zlib1g-dev
COMMIT="400c0e322aae2d3563b4f1fad270fd95a878ba15"
git clone --recursive https://github.com/mcveanlab/mccortex
cd mccortex
git checkout "$COMMIT"
make all MAXK=31
```

And I get the following error

```
../htslib/libhts.a(cram_io.o): In function `lzma_mem_deflate':
/root/mccortex/libs/htslib/cram/cram_io.c:678: undefined reference to `lzma_stream_buffer_bound'
/root/mccortex/libs/htslib/cram/cram_io.c:684: undefined reference to `lzma_easy_buffer_encode'
../htslib/libhts.a(cram_io.o): In function `cram_compress_by_method':
/root/mccortex/libs/htslib/cram/cram_io.c:1040: undefined reference to `BZ2_bzBuffToBuffCompress'
../htslib/libhts.a(cram_io.o): In function `cram_uncompress_block':
/root/mccortex/libs/htslib/cram/cram_io.c:966: undefined reference to `BZ2_bzBuffToBuffDecompress'
../htslib/libhts.a(cram_io.o): In function `lzma_mem_inflate':
/root/mccortex/libs/htslib/cram/cram_io.c:700: undefined reference to `lzma_easy_decoder_memusage'
/root/mccortex/libs/htslib/cram/cram_io.c:700: undefined reference to `lzma_stream_decoder'
/root/mccortex/libs/htslib/cram/cram_io.c:715: undefined reference to `lzma_code'
/root/mccortex/libs/htslib/cram/cram_io.c:728: undefined reference to `lzma_code'
/root/mccortex/libs/htslib/cram/cram_io.c:737: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'bin/dnacat' failed
make[2]: *** [bin/dnacat] Error 1
make[2]: Leaving directory '/root/mccortex/libs/seq_file'
Makefile:49: recipe for target 'seq_file' failed
make[1]: *** [seq_file] Error 2
make[1]: Leaving directory '/root/mccortex/libs'
Makefile:238: recipe for target 'libs-core' failed
make: *** [libs-core] Error 2
```

**Comment by mbhall88** [comment]
Fixed by running `apt install -y r-base-core`.  

Might be a good idea to pop this somewhere in the README.

**Comment by noporpoise** [comment]
I've added a note to the README in #77.
